package com.thirdeye3.webscrapper.utils;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

import com.thirdeye3.webscrapper.dtos.Stock;

@Component
public class PropertyLoader {

    private Integer noOfStocks;
    private List<Stock> stockList;
    private LocalTime marketStart;
    private LocalTime marketEnd;

    public PropertyLoader() {
        stockList = new ArrayList<>();
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
//        stockList.add(new Stock(1, "RELIANCE", "NSE", null, null));
//        stockList.add(new Stock(2, "TCS", "NSE", null, null));
//        stockList.add(new Stock(3, "INFY", "NSE", null, null));
//        stockList.add(new Stock(4, "AAPL", "NASDAQ", null, null));
//        stockList.add(new Stock(5, "GOOGL", "NASDAQ", null, null));
        noOfStocks = stockList.size();
        marketStart = LocalTime.of(9, 14, 30);
        marketEnd = LocalTime.of(15, 30, 30);
    }

    public Integer getNoOfStocks() {
        return noOfStocks;
    }

    public List<Stock> getStockList() {
        return stockList;
    }

	public LocalTime getMarketStart() {
		return marketStart;
	}

	public LocalTime getMarketEnd() {
		return marketEnd;
	}
}
